### ISSUE TITLE
Bug - acces marques

### ISSUE THREAD

**Issue by simple-acces** [RonanDrouglazet/Iberia#8]
Après avoir changé Gvine Nouaison. J'ai beau tout essayer je ne peux plus acceder a Gvine floraison. Quand je clique dessus via le menu j'arrive sur Nouaison

**Comment by RonanDrouglazet** [comment]
ok je look, semble effectivement qu'il y ai un souci à ce niveau, pas sûr du tout que ce sois de ta faute ;)

**Comment by RonanDrouglazet** [comment]
je confirme, tu n'y est pour rien, j'ai le même prob sur Renaissance-Spirits
